// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
          
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbvPDX4yG3qwnsxGA9BKxNDPHxbX_-59Q',
    appId: '1:908985794469:web:ed05fbd40d959288a3724c',
    messagingSenderId: '908985794469',
    projectId: 'kitchen-3b7e9',
    authDomain: 'kitchen-3b7e9.firebaseapp.com',
    storageBucket: 'kitchen-3b7e9.firebasestorage.app',
    measurementId: 'G-G8EBMZHND2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAvLxwy19KDzMl20Q0VL8XEaBNPxg5FFA',
    appId: '1:908985794469:android:adf0c0c320a4dc5ca3724c',
    messagingSenderId: '908985794469',
    projectId: 'kitchen-3b7e9',
    storageBucket: 'kitchen-3b7e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKNquczR6cwU9FAHnPzG5KFmw4h2-DNA0',
    appId: '1:908985794469:ios:a4bed26ca2b782aea3724c',
    messagingSenderId: '908985794469',
    projectId: 'kitchen-3b7e9',
    storageBucket: 'kitchen-3b7e9.firebasestorage.app',
    iosBundleId: 'com.example.ilkWebProjem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKNquczR6cwU9FAHnPzG5KFmw4h2-DNA0',
    appId: '1:908985794469:ios:a4bed26ca2b782aea3724c',
    messagingSenderId: '908985794469',
    projectId: 'kitchen-3b7e9',
    storageBucket: 'kitchen-3b7e9.firebasestorage.app',
    iosBundleId: 'com.example.ilkWebProjem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbvPDX4yG3qwnsxGA9BKxNDPHxbX_-59Q',
    appId: '1:908985794469:web:bcf58852c8deb65da3724c',
    messagingSenderId: '908985794469',
    projectId: 'kitchen-3b7e9',
    authDomain: 'kitchen-3b7e9.firebaseapp.com',
    storageBucket: 'kitchen-3b7e9.firebasestorage.app',
    measurementId: 'G-17H1B4EDD0',
  );
}
